command_timeout = 1000

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$aws\
$azure\
$gcloud\
$vcsh\
$fossil_branch\
${custom.git_server}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#394260 bg:#212736)\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$openstack\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$time\
[ ](fg:#1d2230)\
$character"""
add_newline = false

# Palette
palette = 'tokyo_night'

[palettes.tokyo_night]
color_bg1 = "#1a1b26"
color_bg3 = "#24283b"
color_blue = "#7aa2f7"
color_aqua = "#73daca"
color_yellow = "#e0af68"
color_orange = "#ff9e64"
color_red = "#f7768e"
color_purple = "#bb9af7"
color_white = "#a9b1d6"
color_bright_white = "#e3e5e5"
color_dimmed_white = "#a0a9cb"
color_bright_black = "#414868"

################################################################################
## Custom Commands
################################################################################
[custom.git_server]
#disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "white"
format = '[$output]($style) '

[custom.git_scope]
disabled = true
command = '''
printf "%s (%s)" \
  "$(if [ -n "$GIT_AUTHOR_EMAIL" ]; then echo "$GIT_AUTHOR_EMAIL"; else git config user.email; fi)" \
  "$(if [ -n "$GIT_AUTHOR_NAME" ]; then echo "$GIT_AUTHOR_NAME"; else git config user.name; fi)"
'''
description = 'The currently configured Git user.{email,name}'
format = '$output '
style = 'blue bold'
when = 'git rev-parse --is-inside-work-tree'

[custom.git_last_commit]
disabled = true
description = "Display last commit hash and message"
command = "git show -s --format='%h \"%s\"'"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "bright-yellow bold"
format = "[$output]($style) "

[custom.ssh_no_keys]
disabled = true
description = "SSH missing keys"
when = "ssh-add -l | grep -q 'no identities'"
command = "echo 🚫"
format = '\[$symbol[$output]($style)\]'
shell = ["bash", "--noprofile", "--norc"]
symbol = "🔑"
style = "bold fg:red"

[custom.ssh_keys]
disabled = true
description = "SSH key count"
when = "ssh-add -l | grep -v -q 'no identities'"
command = "ssh-add -l | grep -v 'no identities' | wc -l"
format = '\[$symbol[$output]($style)\]'
shell = ["bash", "--noprofile", "--norc"]
symbol = "🔑"
style = "bold fg:green"

################################################################################
## Shell
################################################################################
[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = " ⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = '[ λ](#7bff00) '
error_symbol = '[ λ](#ff1e00) '

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = '\[[⏱ $duration]($style)\]'
style = 'yellow'

# [memory_usage]
# format = '\[$symbol[${ram}( | ${swap})]($style)\]'
# threshold = 70
# style = "bold dimmed white"
# disabled = false
# 
[time]
# disabled = false
# time_format = "%T"
# style = "bg:#1d2230"
# format = '[[ 🕙 $time ](bg:#1C3A5E fg:#ffffff)]($style)'
# Tokyo-night theme
# 
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[username]
show_always = true
style_user = "bg:color_orange fg:color_bg1"
style_root = "bg:color_orange fg:color_red"
format = '[ $user]($style)'

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
# trim_at = "-"
style = "bold dimmed white"
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = "  "
".aws" = " "

################################################################################
## GIT
################################################################################
[git_branch]
# format = '\[[$symbol$branch]($style)\]'
symbol = '🌱 '
# style = "bold green"
# tokyo-night theme
#
# symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_state]
# format = '\[[\($state( $progress_current of $progress_total)\)]($style)\]'
format = '\[[\($state( $progress_current of $progress_total)\)]($style)\](fg:#769ff0 bg:#394260)]($style)'
# tokyo-night theme
#
style = "bg:#394260"
# format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_status]
conflicted = "⚔️ "
ahead = "💨  ${count} "
behind = "🐢  ${count} "
diverged = "🔱 💨  ${ahead_count} 🐢  ${behind_count} "
untracked = "🛤️  ${count} "
stashed = "📦 "
modified = "📝  ${count} "
staged = "🗃️  ${count} "
renamed = "📛  ${count} "
deleted = "🗑️  ${count} "
style = "bright-white"
format = '\[ $all_status $ahead_behind\]'

[git_commit]
commit_hash_length = 8
style = "bold white"
tag_symbol = '🔖 '
disabled = false

################################################################################
## Languages & Tools
################################################################################
[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
style = 'fg:#ff9e00 bg:#000000'
symbol = '  '

[aws.region_aliases]
ap-southeast-2 = 'apse2'
us-east-1 = 'use1'
us-east-2 = 'use2'

[azure]
disabled = false
format = '[$symbol($username )($subscription)]($style)'
symbol = ' ﴃ '
style = 'fg:#e3e5e5 bg:#769ff0'

[azure.subscription_aliases]
'Waltodders Azure Sub 1' = 'wt-az-sub-1'

[bun]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
symbol = " "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '[$symbol$account(@$domain)(\($project\))]($style)'
symbol = '️  '
# style = 'fg:#ffcc00 bg:#ff0000'
# #style = 'fg:#0066ff bg:#ff0000'
# #style = 'fg:#FFFFFF bg:#3B76F0'
# disabled = false

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[line_break]
disabled = true

[lua]
format = '\[[$symbol($version)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "bold green"
pyenv_version_name = false
detect_extensions = ['py', 'ipynb']

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = " "
format = '\[[$symbol($version)]($style)\]'
style = "bold green"

[scala]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]\]'

[swift]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[vagrant]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
